# Generated by Django 4.2.1 on 2026-09-07 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OpenBench', '0013_nps_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLRHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.IntegerField()),
                ('llr', models.FloatField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llr_history', to='OpenBench.test')),
            ],
            options={
                'ordering': ['games'],
            },
        ),
        migrations.AddConstraint(
            model_name='llrhistory',
            constraint=models.UniqueConstraint(fields=('test', 'games'), name='unique_test_llr_games'),
        ),
    ]
